export const loginTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
};

export const bigFiveTypes = {
  GET_TEMPLATE: "GET_TEMPLATE",
  UPDATE_TEMPLATE: "UPDATE_TEMPLATE",
  REQUEST_FAILED: "REQUEST_FAILED",
};
