export const loginTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
};

export const bigFiveTypes = {
  GET_TEMPLATE: "GET_TEMPLATE",
  UPDATE_TEMPLATE: "UPDATE_TEMPLATE",
  SET_COMPLETE: "SET_COMPLETE",
  SET_START_DIALOG_OPEN: "SET_START_DIALOG_OPEN",
  SET_END_DIALOG_OPEN: "SET_END_DIALOG_OPEN",
  SET_HAS_ERROR: "SET_HAS_ERROR",
  REQUEST_FAILED: "REQUEST_FAILED",
};
