export const rootTypes = {
  DESTROY_SESSION: "DESTROY_SESSION",
};

export const loginTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  PROFILE_UPDATE: "PROFILE_UPDATE",
};

export const bigFiveTypes = {
  BF_GET_TEMPLATE: "BF_GET_TEMPLATE",
  BF_UPDATE_TEMPLATE: "BF_UPDATE_TEMPLATE",
  BF_SET_START_DIALOG_OPEN: "BF_SET_START_DIALOG_OPEN",
  BF_SET_END_DIALOG_OPEN: "BF_SET_END_DIALOG_OPEN",
  BF_SET_TIME_UP: "BF_SET_TIME_UP",
  BF_CHECK_EXISTS: "BF_CHECK_EXISTS",
  BF_SET_HAS_ERROR: "BF_SET_HAS_ERROR",
  BF_CLEAR: "BF_CLEAR",
};

export const stressTypes = {
  STRESS_GET_TEMPLATE: "STRESS_GET_TEMPLATE",
  STRESS_UPDATE_TEMPLATE: "STRESS_UPDATE_TEMPLATE",
  STRESS_SET_START_DIALOG_OPEN: "STRESS_SET_START_DIALOG_OPEN",
  STRESS_SET_END_DIALOG_OPEN: "STRESS_SET_END_DIALOG_OPEN",
  STRESS_SET_TIME_UP: "STRESS_SET_TIME_UP",
  STRESS_CHECK_EXISTS: "STRESS_CHECK_EXISTS",
  STRESS_SET_HAS_ERROR: "STRESS_SET_HAS_ERROR",
  STRESS_CLEAR: "STRESS_CLEAR",
};

export const storyTypes = {
  STORY_SET_END_DIALOG_OPEN: "STORY_SET_END_DIALOG_OPEN",
  STORY_CHECK_EXISTS: "STORY_CHECK_EXISTS",
  STORY_CLEAR: "STORY_CLEAR",
};

export const lonelinessTypes = {
  LONELINESS_GET_TEMPLATE: "LONELINESS_GET_TEMPLATE",
  LONELINESS_UPDATE_TEMPLATE: "LONELINESS_UPDATE_TEMPLATE",
  LONELINESS_SET_START_DIALOG_OPEN: "LONELINESS_SET_START_DIALOG_OPEN",
  LONELINESS_SET_END_DIALOG_OPEN: "LONELINESS_SET_END_DIALOG_OPEN",
  LONELINESS_SET_TIME_UP: "LONELINESS_SET_TIME_UP",
  LONELINESS_CHECK_EXISTS: "LONELINESS_CHECK_EXISTS",
  LONELINESS_SET_HAS_ERROR: "LONELINESS_SET_HAS_ERROR",
  LONELINESS_CLEAR: "LONELINESS_CLEAR",
};

export const rmibTypes = {
  RMIB_GET_TEMPLATE: "RMIB_GET_TEMPLATE",
  RMIB_UPDATE_TEMPLATE: "RMIB_UPDATE_TEMPLATE",
  RMIB_SET_START_DIALOG_OPEN: "RMIB_SET_START_DIALOG_OPEN",
  RMIB_SET_END_DIALOG_OPEN: "RMIB_SET_END_DIALOG_OPEN",
  RMIB_SET_TIME_UP: "RMIB_SET_TIME_UP",
  RMIB_SET_HAS_ERROR: "RMIB_SET_HAS_ERROR",
  RMIB_CLEAR: "RMIB_CLEAR",
};
